// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using asp_backend.Data;

#nullable disable

namespace asp_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529044720_AddSellerIdToTickets")]
    partial class AddSellerIdToTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeePermission", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("EmployeeId", "PermissionId")
                        .HasName("employee_permissions_pkey");

                    b.HasIndex("PermissionId");

                    b.ToTable("employee_permissions", (string)null);
                });

            modelBuilder.Entity("Favorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("UserId", "EventId")
                        .HasName("favorites_pkey");

                    b.HasIndex("EventId");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.AreaSeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EventAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_area_id");

                    b.Property<DateTime?>("ReservedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reserved_at");

                    b.Property<string>("RowLabel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("row_label");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("seat_number");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sold_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'available'::character varying");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("area_seats_pkey");

                    b.HasIndex("TicketId");

                    b.HasIndex(new[] { "EventAreaId" }, "idx_area_seats_area");

                    b.HasIndex(new[] { "Status" }, "idx_area_seats_status");

                    b.HasIndex(new[] { "UserId" }, "idx_area_seats_user");

                    b.HasIndex(new[] { "EventAreaId", "SeatNumber" }, "uq_area_seat_number")
                        .IsUnique();

                    b.ToTable("area_seats", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("employees_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<DateTime?>("SaleEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sale_end");

                    b.Property<DateTime?>("SaleStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sale_start");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.HasKey("Id")
                        .HasName("events_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "EventDate" }, "idx_events_date");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.EventArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area_name");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("event_area_pkey");

                    b.HasIndex(new[] { "EventId", "AreaName" }, "uq_event_area_name")
                        .IsUnique();

                    b.ToTable("event_area", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.EventSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("SectionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_name");

                    b.HasKey("Id")
                        .HasName("event_sections_pkey");

                    b.HasIndex("EventId");

                    b.ToTable("event_sections", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("MetricName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_name");

                    b.Property<decimal?>("MetricValue")
                        .HasColumnType("numeric")
                        .HasColumnName("metric_value");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("metrics_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EventId");

                    b.ToTable("metrics", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<bool?>("Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("read");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("permissions_pkey");

                    b.HasIndex(new[] { "Name" }, "permissions_name_key")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Pqr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'OPEN'::character varying");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pqrs_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Status" }, "idx_pqrs_status");

                    b.ToTable("pqrs", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.PqrsResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid?>("PqrsId")
                        .HasColumnType("uuid")
                        .HasColumnName("pqrs_id");

                    b.Property<string>("Response")
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.HasKey("Id")
                        .HasName("pqrs_responses_pkey");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PqrsId");

                    b.ToTable("pqrs_responses", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int>("LastActivity")
                        .HasColumnType("integer")
                        .HasColumnName("last_activity");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("sessions_pkey");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("purchased_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seat_number");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'VALID'::character varying");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tickets_pkey");

                    b.HasIndex("EventId");

                    b.HasIndex("SellerId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "QrCode" }, "idx_tickets_qr");

                    b.HasIndex(new[] { "QrCode" }, "tickets_qr_code_key")
                        .IsUnique();

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.TicketScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scanned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ScannedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("scanned_by");

                    b.Property<bool?>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("success");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("ticket_scans_pkey");

                    b.HasIndex("ScannedBy");

                    b.HasIndex(new[] { "TicketId" }, "idx_ticket_scans_ticket");

                    b.ToTable("ticket_scans", (string)null);
                });

            modelBuilder.Entity("asp_backend.models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("profile_image");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EmployeePermission", b =>
                {
                    b.HasOne("asp_backend.models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("employee_permissions_employee_id_fkey");

                    b.HasOne("asp_backend.models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("employee_permissions_permission_id_fkey");
                });

            modelBuilder.Entity("Favorite", b =>
                {
                    b.HasOne("asp_backend.models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("favorites_event_id_fkey");

                    b.HasOne("asp_backend.models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("favorites_user_id_fkey");
                });

            modelBuilder.Entity("asp_backend.models.AreaSeat", b =>
                {
                    b.HasOne("asp_backend.models.EventArea", "EventArea")
                        .WithMany("AreaSeats")
                        .HasForeignKey("EventAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_area_seats_area");

                    b.HasOne("asp_backend.models.Ticket", "Ticket")
                        .WithMany("AreaSeats")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_area_seats_ticket");

                    b.HasOne("asp_backend.models.User", "User")
                        .WithMany("AreaSeats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_area_seats_user");

                    b.Navigation("EventArea");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("asp_backend.models.Employee", b =>
                {
                    b.HasOne("asp_backend.models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("employees_role_id_fkey");

                    b.HasOne("asp_backend.models.User", "User")
                        .WithMany("Employees")
                        .HasForeignKey("UserId")
                        .HasConstraintName("employees_user_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("asp_backend.models.Event", b =>
                {
                    b.HasOne("asp_backend.models.Employee", "CreatedByNavigation")
                        .WithMany("Events")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("events_created_by_fkey");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("asp_backend.models.EventArea", b =>
                {
                    b.HasOne("asp_backend.models.Event", "Event")
                        .WithMany("EventAreas")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_area_event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("asp_backend.models.EventSection", b =>
                {
                    b.HasOne("asp_backend.models.Event", "Event")
                        .WithMany("EventSections")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("event_sections_event_id_fkey");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("asp_backend.models.Metric", b =>
                {
                    b.HasOne("asp_backend.models.Employee", "CreatedByNavigation")
                        .WithMany("Metrics")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("metrics_created_by_fkey");

                    b.HasOne("asp_backend.models.Event", "Event")
                        .WithMany("Metrics")
                        .HasForeignKey("EventId")
                        .HasConstraintName("metrics_event_id_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("asp_backend.models.Notification", b =>
                {
                    b.HasOne("asp_backend.models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("asp_backend.models.Pqr", b =>
                {
                    b.HasOne("asp_backend.models.User", "User")
                        .WithMany("Pqrs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("pqrs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("asp_backend.models.PqrsResponse", b =>
                {
                    b.HasOne("asp_backend.models.Employee", "Employee")
                        .WithMany("PqrsResponses")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("pqrs_responses_employee_id_fkey");

                    b.HasOne("asp_backend.models.Pqr", "Pqrs")
                        .WithMany("PqrsResponses")
                        .HasForeignKey("PqrsId")
                        .HasConstraintName("pqrs_responses_pqrs_id_fkey");

                    b.Navigation("Employee");

                    b.Navigation("Pqrs");
                });

            modelBuilder.Entity("asp_backend.models.Ticket", b =>
                {
                    b.HasOne("asp_backend.models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .HasConstraintName("tickets_event_id_fkey");

                    b.HasOne("asp_backend.models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .HasConstraintName("tickets_seller_id_fkey");

                    b.HasOne("asp_backend.models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("tickets_user_id_fkey");

                    b.Navigation("Event");

                    b.Navigation("Seller");

                    b.Navigation("User");
                });

            modelBuilder.Entity("asp_backend.models.TicketScan", b =>
                {
                    b.HasOne("asp_backend.models.Employee", "ScannedByNavigation")
                        .WithMany("TicketScans")
                        .HasForeignKey("ScannedBy")
                        .HasConstraintName("ticket_scans_scanned_by_fkey");

                    b.HasOne("asp_backend.models.Ticket", "Ticket")
                        .WithMany("TicketScans")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("ticket_scans_ticket_id_fkey");

                    b.Navigation("ScannedByNavigation");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("asp_backend.models.Employee", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Metrics");

                    b.Navigation("PqrsResponses");

                    b.Navigation("TicketScans");
                });

            modelBuilder.Entity("asp_backend.models.Event", b =>
                {
                    b.Navigation("EventAreas");

                    b.Navigation("EventSections");

                    b.Navigation("Metrics");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("asp_backend.models.EventArea", b =>
                {
                    b.Navigation("AreaSeats");
                });

            modelBuilder.Entity("asp_backend.models.Pqr", b =>
                {
                    b.Navigation("PqrsResponses");
                });

            modelBuilder.Entity("asp_backend.models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("asp_backend.models.Ticket", b =>
                {
                    b.Navigation("AreaSeats");

                    b.Navigation("TicketScans");
                });

            modelBuilder.Entity("asp_backend.models.User", b =>
                {
                    b.Navigation("AreaSeats");

                    b.Navigation("Employees");

                    b.Navigation("Notifications");

                    b.Navigation("Pqrs");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
